-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 20:59:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation_game_online` DEFAULT CHARACTER SET utf8 ;
USE `db_generation_game_online` ;

-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_classe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `combatente` VARCHAR(45) NULL,
  `conjurador` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);

SELECT * FROM db_generation_game_online.tb_classe;
insert into tb_classe (nome, combatente, conjurador)
values
("Magos", false, true),
("Paladinhos", true, true),
("Vikings", true, false);

-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_personagem` (
  `id_personagem` INT NOT NULL auto_increment,  
  `nome` VARCHAR(25) NOT NULL,
  `velocidade` INT NULL,
  `poder_de_ataque` INT NULL,
  `poder_de_defesa` INT NULL,
  `resistencia` INT NULL,
  `fk_classe` INT NOT NULL,
  PRIMARY KEY (`id_personagem`, `fk_classe`),
  INDEX `fk_category_1_tb_classe_idx` (`fk_classe` ASC) VISIBLE,
  CONSTRAINT `fk_category_1_tb_classe`
    FOREIGN KEY (`fk_classe`)
    REFERENCES `db_generation_game_online`.`tb_classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SELECT * FROM db_generation_game_online.tb_personagem;
insert into tb_personagem (nome, velocidade, poder_de_ataque, poder_de_defesa, resistencia, fk_classe)
values
("Claudio", 70, 1500, 2000, 1500, 1),
("Ivan", 98, 2100, 1800, 1000, 2),
("Isabel", 100, 1500, 1200, 1800, 3);

SELECT * FROM db_generation_game_online.tb_personagem;
SELECT * FROM db_generation_game_online.tb_personagem where poder_de_ataque > 2000;
SELECT * FROM db_generation_game_online.tb_personagem where poder_de_defesa between 1000 and 2000;
SELECT * FROM db_generation_game_online.tb_personagem where nome like "%C%"; 
SELECT * FROM tb_personagem INNER JOIN tb_classe on tb_classe.id = tb_personagem.fk_classe;  
SELECT * FROM tb_personagem INNER JOIN tb_classe on tb_classe.id = tb_personagem.fk_classe WHERE tb_classe.nome LIKE "Magos";

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
