-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 17:50:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_farmacia_do_bem` DEFAULT CHARACTER SET utf8 ;
USE `db_farmacia_do_bem` ;

-- -----------------------------------------------------
-- Table `db_farmacia_do_bem`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem`.`tb_categoria` (
  `id_cat` INT NOT NULL AUTO_INCREMENT,
  `tarja_preta` TINYINT NOT NULL,
  `tarja_vermelha` TINYINT NOT NULL,
  `nao_tarjado` TINYINT NOT NULL,
  PRIMARY KEY (`id_cat`),
  UNIQUE INDEX `id_cat_UNIQUE` (`id_cat` ASC) VISIBLE);

SELECT * FROM db_farmacia_do_bem.tb_categoria;
INSERT INTO tb_categoria (tarja_preta, tarja_vermelha, nao_tarjado)
VALUES
(true, false, false),
(false, true, false),
(false, false, true);

-- -----------------------------------------------------
-- Table `db_farmacia_do_bem`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem`.`tb_produto` (
  `id_prod` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `qntd` INT NOT NULL,
  `preco` INT NOT NULL,
  `fk_cat` INT NOT NULL,
  PRIMARY KEY (`id_prod`, `fk_cat`),
  UNIQUE INDEX `id_UNIQUE` (`id_prod` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_categoria_idx` (`fk_cat` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`fk_cat`)
    REFERENCES `db_farmacia_do_bem`.`tb_categoria` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SELECT * FROM db_farmacia_do_bem.tb_produto;
INSERT INTO tb_produto (nome, qntd, preco, fk_cat)
VALUES
("rivotril", 1, 30,1),
("sinvastatina", 1, 10,2),
("tylenol", 1, 15,3);

SELECT * FROM db_farmacia_do_bem.tb_produto;
SELECT * FROM db_farmacia_do_bem.tb_produto where preco > 50;
SELECT * FROM db_farmacia_do_bem.tb_produto where preco between 3 and 60;
SELECT * FROM db_farmacia_do_bem.tb_produto where nome like "B%";
SELECT * FROM tb_produto INNER JOIN tb_categoria on tb_categoria.id_cat = tb_produto.fk_cat;
SELECT * FROM tb_produto INNER JOIN tb_categoria on tb_categoria.id_cat = tb_produto.fk_cat where tb_categoria.tarja_preta;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
