-- MySQL Script generated by MySQL Workbench
-- Thu Apr 22 21:55:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_estoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_estoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_estoque` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_estoque` ;

-- -----------------------------------------------------
-- Table `db_estoque`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estoque`.`tb_produtos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `tamanho` VARCHAR(5) NOT NULL,
  `preço` BIGINT NULL DEFAULT NULL,
  `ativo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

insert into db_estoque.tb_produtos (nome, tamanho, preço, ativo)
values
("TV", "50 p", "2500", true),
("Freezer", "G", "3500", true),
("Sofá", "G", "3500", false),
("Airfryer", "3L", "300", false),
("Celular", "5p", "2800", true),
("Notebook", "15", "4800", true),
("Guarda Roupa", "3M", "1750", false),
("Cama Box", "QS", "1250", true);

select * from db_estoque.tb_produtos;
select * from db_estoque.tb_produtos where preço > 500;
select * from db_estoque.tb_produtos where preço < 500;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
